name: Create a CD/RO release from a template
description: Create a release on a remote CloudBees CD/RO instance from a self-service catalog item
branding:
  icon: 'command'
  color: 'blue'
  
inputs:
  templateProjectName:
    description: The template catalog project name
    required: true
  templateCatalogName:
    description: The template catalog name
    required: true
  templateName:
    description: The template name
    required: true
  actualParameter:
    required: false
  ignore-unverified-cert:
    description: Ignore unverified SSL certificate errors when connecting to CloudBees CD/RO instance
    default: 'false'
    required: false
  
runs:
  using: "composite"
  steps:
    - name: runCatalogItem API
      uses: cloudbees-github-actions/eval-dsl@v1
      with:
        dsl: runCatalogItem args
        dsl-args: |
          projectName: ${{ inputs.templateProjectName }}
          catalogName: ${{ inputs.templateCatalogName }}
          catalogItemName: ${{ inputs.templateName }}
        dsl-actual-parameter: ${{ inputs.actualParameter }}
        ignore-unverified-cert: ${{ inputs.ignore-unverified-cert }}
